

var Channels = {
    JOIN_PLAYER:"JOIN_PLAYER",
    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_QUEUED: "PLAYER_QUEUED",
    LOBBY_FULLED: "LOBBY_FULLED",
    ROUND_START: "ROUND_START",
    SET_ROUND: "SET_ROUND",
    CARD_PLAYED: "CARD_PLAYED",
    HAND_FINISHED:"HAND_FINISHED",
    TRUMP_OPEN:"TRUMP_OPEN",
    TEST: "TEST"
};

module.exports = Channels;